INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Zoom', 'Software', 5000, '2/4/2018', '10/4/2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Coffee', 'Beverages', 20, '8/2/2018', '10/1/2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Cats', 'Pets', 1000, '9/4/2018', '11/14/2018');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Crayons', 'Supplies', 80, '12/4/2018', '1/4/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('PCRecruiter', 'Software', 2000, '6/30/2019', '10/21/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Dogs', 'Pets', 1500, '12/4/2018', '10/4/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Beer', 'Beverages', 520, '5/10/2019', '1/14/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Tesla', 'Cars', 800000, '7/4/2019', '1/5/2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Bridges', 'Infastructure', 5000000, '9/30/2018', '12/3/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Paper', 'Supplies', 50, '2/4/2018', '10/4/2018');

INSERT INTO users (name, age) VALUES ('Debi', 48);
INSERT INTO users (name, age) VALUES ('Walter', 20);
INSERT INTO users (name, age) VALUES ('Liz', 27);
INSERT INTO users (name, age) VALUES ('Maggie', 26);
INSERT INTO users (name, age) VALUES ('Rob', 22);
INSERT INTO users (name, age) VALUES ('Taylor', 18);
INSERT INTO users (name, age) VALUES ('Erin', 20);
INSERT INTO users (name, age) VALUES ('Chuck', 58);
INSERT INTO users (name, age) VALUES ('Chuch', 32);
INSERT INTO users (name, age) VALUES ('Steven', 38);
INSERT INTO users (name, age) VALUES ('Isabella', 23);
INSERT INTO users (name, age) VALUES ('Diana', 35);
INSERT INTO users (name, age) VALUES ('Eric', 37);
INSERT INTO users (name, age) VALUES ('Eric', 28);
INSERT INTO users (name, age) VALUES ('Jen', 43);
INSERT INTO users (name, age) VALUES ('Alcia', 30);
INSERT INTO users (name, age) VALUES ('Maxim', 25);
INSERT INTO users (name, age) VALUES ('Jill', 26);
INSERT INTO users (name, age) VALUES ('Genevieve', 30);
INSERT INTO users (name, age) VALUES ('Tom', 32);

INSERT INTO pledges (user_id, project_id, amount) VALUES (1, 1, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2, 1, 250);
INSERT INTO pledges (user_id, project_id, amount) VALUES (3, 10, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 6, 500);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5, 1, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (10, 1, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (9, 1, 250);
INSERT INTO pledges (user_id, project_id, amount) VALUES (8, 10, 350);
INSERT INTO pledges (user_id, project_id, amount) VALUES (7, 20, 500);
INSERT INTO pledges (user_id, project_id, amount) VALUES (6, 19, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (1, 1, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2, 1, 250);
INSERT INTO pledges (user_id, project_id, amount) VALUES (3, 10, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 6, 500);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5, 1, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (10, 1, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (9, 1, 250);
INSERT INTO pledges (user_id, project_id, amount) VALUES (8, 10, 350);
INSERT INTO pledges (user_id, project_id, amount) VALUES (7, 20, 500);
INSERT INTO pledges (user_id, project_id, amount) VALUES (6, 19, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (1, 1, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2, 1, 250);
INSERT INTO pledges (user_id, project_id, amount) VALUES (3, 10, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 6, 500);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5, 1, 150);
INSERT INTO pledges (user_id, project_id, amount) VALUES (10, 14, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (9, 15, 250);
INSERT INTO pledges (user_id, project_id, amount) VALUES (8, 10, 350);
INSERT INTO pledges (user_id, project_id, amount) VALUES (7, 2, 500);
INSERT INTO pledges (user_id, project_id, amount) VALUES (6, 9, 50);
